kind: Deployment
apiVersion: apps/v1
metadata:
  name: linked
  namespace:  linked
  labels:
    app.kubernetes.io/name: linked
    app.kubernetes.io/part-of: linked
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: linked
  template:
    metadata:
      labels:
        app.kubernetes.io/name: linked
        app.kubernetes.io/part-of: linked
    spec:
      containers:
      - name: linked
        image: wonyus/linked:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 512Mi
        env:
        - name: NEXTAUTH_URL
          valueFrom:
            configMapKeyRef:
                name: linked
                key: NEXTAUTH_URL
        - name: NEXTAUTH_SECRET
          valueFrom:
            configMapKeyRef:
                name: linked
                key: NEXTAUTH_SECRET
        - name: GITHUB_ID
          valueFrom:
            configMapKeyRef:
                name: linked
                key: GITHUB_ID
        - name: GITHUB_SECRET
          valueFrom:
            configMapKeyRef:
                name: linked
                key: GITHUB_SECRET
        - name: SERVER_URL
          valueFrom:
            configMapKeyRef:
                name: linked
                key: SERVER_URL
        ports:
        - containerPort: 3000